project:
  type: website

website:
  navbar:
    logo: "Picture/Fish.png"
    background: primary
    left:
      - text: "Team"
        menu:
          - text: "Member"
            href: "Team/Member/Member.html"
          - text: "MoM"
            href: "Team/MoM/MoM.html"
      - text: "Proposal"  
        menu: 
          - text: "Proposal"
            href: "Proposal/Proposal.html"
      - text: "Poster"
        href: "https://smu.sharepoint.com/:i:/r/teams/VIsualgroupproject/Shared%20Documents/General/it%27s%20official%20(22.39%20x%2033.11%20%E8%8B%B1%E5%AF%B8)%20(1).jpg?csf=1&web=1&e=f4zz74"
      - text: "Shiny"
        href: "https://jiaxunzou.shinyapps.io/ShinyDemo/"


    right:
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Fnrion/Oceanus
          - text: Report a Bug
            href:  https://bugs.com

      
format:
  html:
    grid:
      margin-width: 180px
    theme:
      light: Cerulean
      dark: Sandstone
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    backgroundcolor: Ivory
    light: flatly
    dark: darkly
editor: visual