project:
  type: website

website:
  navbar:
    logo: "Picture/Fish.png"
    background: primary
    left:
      - text: "Team"
        menu:
          - text: "Member"
            href: "Team/Member/Member.html"
          - text: "MoM"
            href: "Team/MoM/MoM.html"
      - text: "Proposal"  
        menu: 
          - text: "Proposal"
            href: "Proposal/Proposal.html"
    right:
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Fnrion/Oceanus
          - text: Report a Bug
            href:  https://bugs.com
      
format:
  html:
    theme:
      light: Cerulean
      dark: Sandstone
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    backgroundcolor: Ivory
    light: flatly
    dark: darkly
editor: visual