project:
  type: website

website:
  navbar:
    logo: "Picture/Fish.png"
    background: success
    left:
      - text: "Hands-on Exerciese"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-class Exercise"  
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
      - text: "Take-home Exercise"  
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-Home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Fnrion/Oceanus
          - text: Report a Bug
            href:  https://bugs.com
format:
  html:
    theme:
      light: Journal
      dark: cosmo
    toc: true
    fontsize: 0.9em
    linestretch: 1.6
    backgroundcolor: Ivory
    light: flatly
    dark: darkly
editor: visual