---
title: "Proposal"
author: Zhang Chenbin, Zou Jiaxun
date: "May 30, 2024"
data-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## **1. Title**

**Visualization for Fish Companies' Network and Inner Business after Illegally Fishing**

## **2. Motivation**

The commercial fishing industry in Oceanus is marked by dynamic changes, including new startups, mergers, and acquisitions. Recently, the illegal activities of SouthSeafood Express Corp have highlighted the need for robust tools to monitor and analyze these corporate structures. FishEye International, dedicated to preserving the marine ecosystem, requires advanced visualization tools to identify key influencers, detect suspicious activities, and understand the broader market impacts of such illegal actions. 

Our project aims to develop a web-enabled visual analytics application to help FishEye analysts visualize and understand temporal changes in corporate structures and business transactions. By providing clear visual representations of corporate networks and business transactions, the application will enable analysts to identify potential red flags, examine typical and atypical transactions, and understand how corporate influence and ownership evolve over time. This will support FishEye's mission to prevent illegal fishing and ensure the sustainability of Oceanus's marine ecosystem. 

## 3. **Tasks and Questions**

This is based on the tasks and questions from VAST Challenge 2024 Mini Challenge 3. 

A key element in stopping illegal fishing is holding the people who own nefarious companies accountable. Thus, FishEye is keenly interested in developing visualization tools that work with CatchNet to identify the people who hold influence over business networks. That is especially difficult with varied and changing shareholder and ownership relationships.

1.  FishEye analysts want to better visualize changes in corporate structures over time. Create a visual analytics approach that analysts can use to highlight temporal patterns and changes in corporate structures. Examine the most active people and businesses using visual analytics.

2.  Using your visualizations, find and display examples of typical and atypical business transactions (e.g., mergers, acquisitions, etc.). Can you infer the motivations behind changes in their activity?

3.  Develop a visual approach to examine inferences. Infer how the influence of a company changes through time. Can you infer ownership or influence that a network may have?

4.  Identify the network associated with SouthSeafood Express Corp and visualize how this network and competing businesses change as a result of their illegal fishing behavior. Which companies benefited from South Seafood Express Corp legal troubles? Are there other suspicious transactions that may be related to illegal fishing? Provide visual evidence for your conclusions.

## **4. Methodology**

The initial approach involves identifying abnormalities in the data, followed by necessary data wrangling and cleaning. We will conduct initial data exploration and analysis to understand the dataset better. Once this is complete, we will proceed to address each task individually. 

**Task 1: Visualize Changes in Corporate Structures Over Time** 

DHUSIAVDLSAvfldvalfD

**Task 2: Analyze Business Transactions** 

CVXHZJVCJDGSUAGLD

**Task 3: Examine Influence Dynamics** 

fhsuaifgdipagfudipasugpI

**Task 4: Identify Network Changes Related to SouthSeafood Express Corp** 

FHSUIAGFIDPAGifgisagp
